---
output: html_document
---





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r lib, include = FALSE}
library(knitr)
options(knitr.table.format = "html") 

packs <- c('kableExtra','tidyverse')
   need <- packs[!packs %in% installed.packages()[,'Package']]
   if(length(need)>0){install.packages(need)}
   lapply(packs, require, character.only = TRUE)
```   

```{r df, include = FALSE}

tbl_list <- list.files(path = "/Users/elisemiller/R_Projects/kings/data_temp", pattern = "eftblskinny", full.names = T)

   dig_regex <- "[[:digit:]]+"
   
   dw_list <- vector("list", length(grep("drinkingwater",tbl_list)))  
   cc_list <- vector("list", length(grep("CC",tbl_list)))
   ej_list <- vector("list", length(grep("EJ",tbl_list)))
   gde_list <- vector("list", length(grep("GDE",tbl_list)))

   for(i in 1:length(grep("drinkingwater",tbl_list))){
      dw_list[[i]] <- read_csv(tbl_list[grep("drinkingwater",tbl_list)[i]], show_col_types = FALSE)
      #changing small p values to "<0.05"
      p_temp <- dw_list[[i]]$`Pr(>|t|)`
      dw_list[[i]]$`Pr(>|t|)` <- as.character(dw_list[[i]]$`Pr(>|t|)`)
      dw_list[[i]]$`Pr(>|t|)` <-  ifelse(
         p_temp<0.05,"<0.05",as.character(signif(as.numeric(dw_list[[i]]$`Pr(>|t|)`),digits = 2)))
      sig <- dw_list[[i]]$`Pr(>|t|)`=="<0.05"
      dw_list[[i]]$`Pr(>|t|)` <- ifelse(sig, "**","")
      dw_list[[i]]$Estimate <- signif(dw_list[[i]]$Estimate, digits = 3)
      dw_list[[i]]$`Std. Error` <- NULL
      dw_list[[i]]$`t value` <- NULL
         
      #removing var names from even numbered tables so they fit nicely
      if (i %% 2 == 0){
         dw_list[[i]] <- dw_list[[i]][,-1]
      }
   }
   
   dw_topics <- unlist(str_extract_all(strsplit(tbl_list[grep("drinkingwater",tbl_list)], ":")[[1]][2], dig_regex))
   
   for(i in 1:length(grep("CC",tbl_list))){
      cc_list[[i]] <- read_csv(tbl_list[grep("CC",tbl_list)[i]], show_col_types = FALSE)
      #changing small p values to "<0.05"
      p_temp <- cc_list[[i]]$`Pr(>|t|)`
      cc_list[[i]]$`Pr(>|t|)` <- as.character(cc_list[[i]]$`Pr(>|t|)`)
      cc_list[[i]]$`Pr(>|t|)` <-  ifelse(
         p_temp<0.05,"<0.05",as.character(signif(as.numeric(cc_list[[i]]$`Pr(>|t|)`),digits = 2)))
      sig <- cc_list[[i]]$`Pr(>|t|)`=="<0.05" 
      cc_list[[i]]$`Pr(>|t|)` <- ifelse(sig, "**","")
      cc_list[[i]]$Estimate <- signif(cc_list[[i]]$Estimate, digits = 3)
      cc_list[[i]]$`Std. Error` <- NULL
      cc_list[[i]]$`t value` <- NULL
         
      #removing var names from even numbered tables so they fit nicely
      if (i %% 2 == 0){
         cc_list[[i]] <- cc_list[[i]][,-1]
      }
   }
   cc_topics <- unlist(str_extract_all(tbl_list[grep("CC",tbl_list)], dig_regex))
   
   for(i in 1:length(grep("EJ",tbl_list))){
      ej_list[[i]] <- read_csv(tbl_list[grep("EJ",tbl_list)[i]], show_col_types = FALSE)
      #changing small p values to "<0.05"
      p_temp <- ej_list[[i]]$`Pr(>|t|)`
      ej_list[[i]]$`Pr(>|t|)` <- as.character(ej_list[[i]]$`Pr(>|t|)`)
      ej_list[[i]]$`Pr(>|t|)` <-  ifelse(
         p_temp<0.05,"<0.05",as.character(signif(as.numeric(ej_list[[i]]$`Pr(>|t|)`),digits = 2)))
      sig <- ej_list[[i]]$`Pr(>|t|)`=="<0.05" 
      ej_list[[i]]$`Pr(>|t|)` <- ifelse(sig, "**","")
      ej_list[[i]]$Estimate <- signif(ej_list[[i]]$Estimate, digits = 3)
      ej_list[[i]]$`Std. Error` <- NULL
      ej_list[[i]]$`t value` <- NULL
         
      #removing var names from even numbered tables so they fit nicely
      if (i %% 2 == 0){
         ej_list[[i]] <- ej_list[[i]][,-1]
      }
   }
   ej_topics <- unlist(str_extract_all(tbl_list[grep("EJ",tbl_list)], dig_regex))
   
   for(i in 1:length(grep("GDE",tbl_list))){
      gde_list[[i]] <- read_csv(tbl_list[grep("GDE",tbl_list)[i]], show_col_types = FALSE)
      #changing small p values to "<0.05"
      p_temp <- gde_list[[i]]$`Pr(>|t|)`
      gde_list[[i]]$`Pr(>|t|)` <- as.character(gde_list[[i]]$`Pr(>|t|)`)
      gde_list[[i]]$`Pr(>|t|)` <-  ifelse(
         p_temp<0.05,"<0.05",as.character(signif(as.numeric(gde_list[[i]]$`Pr(>|t|)`),digits = 2)))
      sig <- gde_list[[i]]$`Pr(>|t|)`=="<0.05"
      gde_list[[i]]$`Pr(>|t|)` <- ifelse(sig, "**","")
      gde_list[[i]]$Estimate <- signif(gde_list[[i]]$Estimate, digits = 3)
      gde_list[[i]]$`Std. Error` <- NULL
      gde_list[[i]]$`t value` <- NULL
         
      
      #removing var names from even numbered tables so they fit nicely
      if (i %% 2 == 0){
         gde_list[[i]] <- gde_list[[i]][,-1]
      }
   }
   gde_topics <- unlist(str_extract_all(tbl_list[grep("GDE",tbl_list)], dig_regex))
```


```{r list, results = 'asis', echo = FALSE}
#list solution
    

#center the last table
#header labels table with topic number
cap <- "<center><strong>Prevalence of Drinking Water Topics</strong></center>"
knitr::kable(dw_list[[length(dw_list)]], "html", digits = getOption("digits"), row.names = NA,
  col.names = NA, align = "c", caption = cap, label = NULL,
escape = FALSE) %>% kable_styling("condensed", full_width = FALSE) %>% 
      add_header_above(c(setNames(length(dw_list[[length(dw_list)]]), paste0("Topic ",dw_topics,collapse="+")))) 
   
   if(length(cc_list)>1){
         for(i in 1:floor(length(cc_list)/2)){
#      #print 2 tables side by side at a time
   library(kableExtra)
   t1 <- cc_list[[2*i-1]]
   t2 <- cc_list[[2*i]]
   cap <- "<center><strong>Prevalence of Climate Change Topics</strong></center>"
     print(knitr::kables(list(
        knitr::kable(t1, format = "html", digits = getOption("digits"), align = "l", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_left")  ,   
        knitr::kable(t2, format = "html", digits = getOption("digits"), align = "r", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_right")), caption = ifelse(i==1,cap,"") ) %>% add_header_above(c(paste0("Topic ",cc_topics[2*i-1]),paste0("Topic ",cc_topics[2*i]))))
}
   }
     
   if(floor(length(cc_list)/2)!=ceiling(length(cc_list)/2)){
      #center the last table if there are an odd number of tables
      #header labels table with topic number
      knitr::kable(cc_list[[length(cc_list)]], "html", digits = getOption("digits"), row.names = NA,
  col.names = NA, align = "c", caption = NULL, label = NULL,
escape = FALSE) %>% kable_styling("condensed", full_width = FALSE) %>% 
      add_header_above(c(setNames(length(cc_list[[length(cc_list)]]), paste0("Topic ",cc_topics[length(cc_topics)]))))
   }

if(length(ej_list)>1){
         for(i in 1:floor(length(ej_list)/2)){
#      #print 2 tables side by side at a time
   library(kableExtra)
   t1 <- ej_list[[2*i-1]]
   t2 <- ej_list[[2*i]]
   cap <- "<center><strong>Prevalence of Environmental Justice Topics</strong></center>"
     print(knitr::kables(list(
        knitr::kable(t1, format = "html", digits = getOption("digits"), align = "l", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_left")  ,   
        knitr::kable(t2, format = "html", digits = getOption("digits"), align = "r", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_right")), caption = ifelse(i==1,cap,"") ) %>% add_header_above(c(paste0("Topic ",ej_topics[2*i-1]),paste0("Topic ",ej_topics[2*i]))))
 
}
   }
   
   if(length(gde_list)>1){
         for(i in 1:floor(length(gde_list)/2)){
#      #print 2 tables side by side at a time
   library(kableExtra)
   t1 <- gde_list[[2*i-1]]
   t2 <- gde_list[[2*i]]
   cap <- "<center><strong>Prevalence of Groundwater-Dependent Ecosystem Topics</strong></center>"
     print(knitr::kables(list(
        knitr::kable(t1, format = "html", digits = getOption("digits"), align = "l", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_left")  ,   
        knitr::kable(t2, format = "html", digits = getOption("digits"), align = "r", label = NULL, escape = FALSE) %>% kable_styling(bootstrap_options = c("condensed"),
                            full_width = FALSE, position = "float_right")), caption = ifelse(i==1,cap,"") ) %>% add_header_above(c(paste0("Topic ",gde_topics[2*i-1]),paste0("Topic ",gde_topics[2*i]))))
 
}
   }
     
   if(floor(length(gde_list)/2)!=ceiling(length(gde_list)/2)){
      #center the last table if there are an odd number of tables
      #header labels table with topic number
      knitr::kable(gde_list[[length(gde_list)]], "html", digits = getOption("digits"), row.names = NA,
  col.names = NA, align = "c", caption = NULL, label = NULL,
escape = FALSE) %>% kable_styling("condensed", full_width = FALSE) %>% 
      add_header_above(c(setNames(length(gde_list[[length(gde_list)]]), paste0("Topic ",gde_topics[length(gde_topics)]))))
   }
   

```

```{r results="asis", echo = FALSE}
cat("
<style>
caption {
      color: black;
      font-weight: bold;
      font-size: 1.5em;
    }
</style>
")
```

